import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f9f9ff",
        surface: "#f9f9ff",
        "surface-dim": "#d0daf2",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e8eeff",
        "surface-container-high": "#dfe8ff",
        "surface-container-highest": "#d9e3fb",
        "surface-variant": "#d9e3fb",
        "on-surface": "#111c2d",
        "on-surface-variant": "#3c4a40",
        "on-background": "#111c2d",
        "inverse-surface": "#273143",
        "inverse-on-surface": "#ecf0ff",
        outline: "#6c7b6f",
        "outline-variant": "#bbcabd",
        "surface-tint": "#006d41",
        primary: "#006d41",
        "on-primary": "#ffffff",
        "primary-container": "#34d186",
        "on-primary-container": "#005431",
        "inverse-primary": "#48e093",
        secondary: "#5a5e6b",
        "on-secondary": "#ffffff",
        "secondary-container": "#dcdfef",
        "on-secondary-container": "#5f6270",
        tertiary: "#5c5f61",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b6b9bc",
        "on-tertiary-container": "#46494c",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#6afdad",
        "primary-fixed-dim": "#48e093",
        "on-primary-fixed": "#002110",
        "on-primary-fixed-variant": "#00522f",
        "secondary-fixed": "#dfe2f2",
        "secondary-fixed-dim": "#c3c6d6",
        "on-secondary-fixed": "#171b27",
        "on-secondary-fixed-variant": "#434653",
        "tertiary-fixed": "#e0e3e6",
        "tertiary-fixed-dim": "#c4c7ca",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary-fixed-variant": "#44474a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "32px",
        xl: "48px",
        gutter: "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
